CREATE TABLE User2
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Phone
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	PhonNumber NVARCHAR(50) NOT NULL, 
	UserId INT FOREIGN KEY REFERENCES User2(Id) NOT NULL UNIQUE
)

CREATE TABLE [Message]
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    [Text] NVARCHAR(50) NOT NULL,
    AcountSender INT FOREIGN KEY REFERENCES User2(Id) NOT NULL,
    AcountRecipent INT FOREIGN KEY REFERENCES User2(Id) NOT NULL
);


CREATE TABLE Frends2
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(50) NOT NULL,
	UserId INT FOREIGN KEY REFERENCES User2(Id) NOT NULL
)

CREATE TABLE FrendsAndUser
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	FrendsId INT FOREIGN KEY REFERENCES Frends2(Id) NOT NULL,
	UserId INT FOREIGN KEY REFERENCES User2(Id) NOT NULL
)

DROP TABLE [Message]
DROP TABLE Phone;
DROP TABLE User2